# Generated by Django 3.2.3 on 2021-06-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('from_email', models.EmailField(max_length=254)),
                ('to', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=25)),
            ],
        ),
    ]
