# Generated by Django 3.2.3 on 2021-06-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='to',
            new_name='RECIPIENTS_EMAIL',
        ),
    ]
