# Generated by Django 3.2.3 on 2021-06-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_to_message_recipients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='RECIPIENTS_EMAIL',
            field=models.EmailField(default='vikamusa18@gmail.com', max_length=254, verbose_name='Кому:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='Письмо отправил:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=25, verbose_name='Сообщение:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=25, verbose_name='Тема письма:'),
        ),
    ]
